-- MySQL Script generated by MySQL Workbench
-- 11/08/17 08:19:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `USERID` VARCHAR(30) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `DOB` VARCHAR(10) NOT NULL,
  `PHONE` INT NULL,
  `EMAIL` VARCHAR(256) NULL,
  `ADDRESS` VARCHAR(256) NULL,
  `JOB` VARCHAR(45) NULL,
  `MAJOR` VARCHAR(100) NULL,
  PRIMARY KEY (`USERID`),
  UNIQUE INDEX `USERID_UNIQUE` (`USERID` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `PRODUCTID` VARCHAR(30) NOT NULL,
  `USERID` VARCHAR(30) NOT NULL,
  `TYPEID` VARCHAR(10) NOT NULL,
  `AMOUNT` INT NOT NULL,
  `STARTPRICE` INT NOT NULL,
  `UNITID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`PRODUCTID`),
  UNIQUE INDEX `PRODUCTID_UNIQUE` (`PRODUCTID` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TYPE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TYPE` (
  `TYPEID` VARCHAR(10) NOT NULL,
  `DESCRIPTION` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`TYPEID`));


-- -----------------------------------------------------
-- Table `mydb`.`PASSWORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PASSWORD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PASSWORD` (
  `USERID` VARCHAR(30) NOT NULL,
  `PASSWRD` BINARY(1000) NULL);


-- -----------------------------------------------------
-- Table `mydb`.`UNIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UNIT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UNIT` (
  `UNITID` VARCHAR(10) NOT NULL,
  `DESCRIPTION` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`UNITID`));


-- -----------------------------------------------------
-- Table `mydb`.`AUCTIONDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AUCTIONDETAIL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AUCTIONDETAIL` (
  `AUCTIONID` VARCHAR(10) NOT NULL,
  `SELLER` VARCHAR(10) NOT NULL,
  `BUYER` VARCHAR(10) NULL,
  `LONG` VARCHAR(45) NULL COMMENT 'How long will auction last.',
  `PRODUCTID` VARCHAR(10) NULL,
  `PRICESTEP` INT NULL COMMENT 'a price for each time buyer set price',
  PRIMARY KEY (`AUCTIONID`));


-- -----------------------------------------------------
-- Table `mydb`.`AUCTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AUCTION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AUCTION` (
  `AUCTIONID` VARCHAR(10) NULL,
  `SEQUENCE` INT NOT NULL,
  `PRICE` INT NULL,
  `BUYERID` VARCHAR(10) NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
